### ISSUE TITLE
Explaination of the still served error

### ISSUE THREAD

**Issue by nonbinary** [milesmcc/LibreNews-Server#18]
I'm working on a docker image of the server (current progress at https://hub.docker.com/r/nonbinary/librenews/ )
I'm currently getting an error fetching IP errors. The error message is "still served..."
What does this error mean?

**Comment by milesmcc** [comment]
So what's happening is that LibreNews isn't able to geolocate (at a country level) the requester based on their IP, but because geolocation isn't critical in terms of serving the content, the server says that it `Still served...` the request.

The relevant lines of code are:

https://github.com/milesmcc/LibreNews-Server/blob/9d16a755e4cbab0f876df36f40e66d80ddbbe85d/src/webserver.py#L35-L38

https://github.com/milesmcc/LibreNews-Server/blob/9d16a755e4cbab0f876df36f40e66d80ddbbe85d/src/webserver.py#L56-L60

This may be happening because you don't have `pycountry` or `geoip` (or the associated databases that they pull out of) properly installed. To install these, check out their documentation — it's relatively simple but I don't remember it off the top of my head.

Also, thank you for creating a docker version of LibreNews! That's awesome. I'll keep my eye on your progress. :+1: :smile:

**Comment by milesmcc** [comment]
Let me know if this helps to fix the issue, and if it does, what steps you took so that others in the future can refer to this thread. Thanks!

**Comment by nonbinary** [comment]
I'm getting a 404, and the server says :

    UnboundLocalError: local variable 'req_resp' referenced before assignment

At the moment, I'm thinking it might be a faulty stats package. When I manually try to install stats (on debian Wheezy), pip gives an install error. Will try another dist. 

I'm rather new to docker, but I hope I can swing something useful. I was hoping to create an alpine image, but had some trouble with the python dependencies. Hopefully I'll get that working in the future. Using wheezy  was,  tbh, a mistake. I don't usually work with debian, and got the releases mixed up.
Right now, the image needs to be restarted, and the json file edited. I'm aiming to supply all the API keys as environment variables in the docker image...

**Comment by nonbinary** [comment]
I've tried installing geoip and pycountry from repositories, as well as through pip. I still get 404's due to req_resp getting no value.
The stats package had me confused, I realized that the server is importing its local stats.py file. I've tried dumping values from that file using say() and error(), but it doesn't seem to run from the stats.py file.
I'll keep trying later, but have to work a bit on other projects now.

**Comment by nonbinary** [comment]
After some hacking I think I have part of the issue down.
The try/except clauses that log the "still served" message does not set req_resp in the except clause. This means that if the try clause fails, the variable is unset, and the code fails in later stages. I tested setting req_resp to a nonsense value, and the server started working.
However, when I try to access it through an nginx proxy, I still get 404's, only this time with no meaningful error value.

**Comment by nonbinary** [comment]
After some rather brutal rewriting of the code an its error messages, I discovered that I need the python-geoip-geolite2 from pip. This information was hidden behind one of the except clauses. After changing the code, capturing the original error message, and logging that, I could find out what went wrong.
If I do go ahead with running my own server, I think I'll fork this, and rewrite the error handling.
Right now, my list of packages that need installing, outside of requirements.txt, from pip, are:
pytz pycountry humanize python-geoip-geolite2 geoip
Not sure why these are not in requirements.txt - they're not optional, the server will not run without them.

**Comment by milesmcc** [comment]
Yeah—that's just an oversight. I'll add them now. Thanks for catching!

**Comment by nonbinary** [comment]
I consider this issue resolved, then :) Thank you!
